CREATE TABLE `smart_uploads` (
	`id` int AUTO_INCREMENT NOT NULL,
	`originalFilename` varchar(512) NOT NULL,
	`mimeType` varchar(128) NOT NULL,
	`fileSizeBytes` int NOT NULL,
	`stagingS3Key` varchar(512),
	`stagingS3Url` varchar(1024),
	`finalS3Key` varchar(512),
	`finalS3Url` varchar(1024),
	`status_su` enum('pending','classifying','review','committed','rejected','error') NOT NULL DEFAULT 'pending',
	`aiContentType` enum('book_pdf','book_audio','book_cover','author_avatar','author_bio','article_pdf','podcast_audio','video','research_paper','newsletter','transcript','design_asset','unknown'),
	`aiConfidence` int,
	`aiReasoning` text,
	`aiClassificationJson` text,
	`aiSuggestedAuthorName` varchar(256),
	`matchedAuthorId` int,
	`aiSuggestedBookTitle` varchar(512),
	`matchedBookId` int,
	`targetTable` varchar(64),
	`shouldIndexPinecone` boolean DEFAULT false,
	`pineconeNamespace` varchar(64),
	`shouldMirrorDropbox` boolean DEFAULT true,
	`suggestedDropboxPath` varchar(1024),
	`overrideContentType` varchar(64),
	`confirmedAuthorId` int,
	`confirmedBookId` int,
	`adminNotes` text,
	`committedRecordId` int,
	`errorMessage` text,
	`classifiedAt` timestamp,
	`reviewedAt` timestamp,
	`createdAt_su` timestamp NOT NULL DEFAULT (now()),
	`updatedAt_su` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `smart_uploads_id` PRIMARY KEY(`id`)
);
