/**
 * TermsOfService.tsx
 *
 * Public-facing Terms of Service page for the NCG Library application.
 * Accessible at /terms — no authentication required.
 * Linked from the sidebar footer alongside Privacy Policy and Cookie Policy.
 */

import { Link } from "wouter";
import { ArrowLeft } from "lucide-react";

const LAST_UPDATED = "April 4, 2026";
const CONTACT_EMAIL = "legal@cidale.com";
const APP_NAME = "NCG Library";
const COMPANY_NAME = "Cidale Consulting Group";
const COMPANY_WEBSITE = "https://cidale.com";

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      {/* Top nav */}
      <header className="sticky top-0 z-10 border-b border-border bg-background/80 backdrop-blur-md">
        <div className="max-w-3xl mx-auto px-6 py-4 flex items-center gap-3">
          <Link href="/">
            <button className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors">
              <ArrowLeft className="w-4 h-4" />
              Back to Library
            </button>
          </Link>
          <span className="text-muted-foreground">·</span>
          <span className="text-sm font-medium">{APP_NAME} — Terms of Service</span>
        </div>
      </header>

      {/* Content */}
      <main className="max-w-3xl mx-auto px-6 py-12 space-y-10">
        {/* Title block */}
        <div className="space-y-2">
          <h1 className="text-3xl font-bold tracking-tight">Terms of Service</h1>
          <p className="text-sm text-muted-foreground">Last updated: {LAST_UPDATED}</p>
        </div>

        <Section title="1. Acceptance of Terms">
          <p>
            By accessing or using {APP_NAME} (the "Service"), operated by{" "}
            <strong>{COMPANY_NAME}</strong> ("we", "us", or "our"), you agree to be bound by these
            Terms of Service ("Terms"). If you do not agree to these Terms, please do not use the
            Service. We reserve the right to update these Terms at any time — continued use of the
            Service after changes are posted constitutes your acceptance of the revised Terms.
          </p>
        </Section>

        <Section title="2. Description of Service">
          <p>
            {APP_NAME} is a private digital library application that aggregates author profiles,
            book metadata, audiobooks, and curated media content for personal knowledge management.
            The Service includes AI-powered features such as author research, book summaries, and
            personalised recommendations. The Service is intended for private, non-commercial use
            by authorised users only.
          </p>
        </Section>

        <Section title="3. Eligibility and Access">
          <p>
            Access to the Service is restricted to authorised users who have been granted access by
            the Service operator. You must be at least 13 years of age to use the Service. By using
            the Service, you represent and warrant that you meet these eligibility requirements.
          </p>
          <p>
            We reserve the right to suspend or terminate your access at any time, with or without
            notice, for any reason including but not limited to a violation of these Terms.
          </p>
        </Section>

        <Section title="4. User Responsibilities">
          <p>You agree to use the Service only for lawful purposes and in a manner consistent with these Terms. Specifically, you agree not to:</p>
          <ul className="list-disc list-inside space-y-1 text-sm">
            <li>Attempt to gain unauthorised access to any part of the Service or its infrastructure.</li>
            <li>Use automated tools, bots, or scrapers to extract data from the Service at scale.</li>
            <li>Reverse-engineer, decompile, or disassemble any part of the Service.</li>
            <li>Upload, transmit, or distribute any content that is unlawful, harmful, or infringes third-party intellectual property rights.</li>
            <li>Interfere with or disrupt the integrity or performance of the Service.</li>
          </ul>
        </Section>

        <Section title="5. Intellectual Property">
          <p>
            All content generated by the Service — including AI-generated author summaries, enrichment
            data, and interface design — is the property of {COMPANY_NAME} or its licensors. You may
            not reproduce, distribute, or create derivative works from this content without prior
            written permission.
          </p>
          <p>
            Content sourced from third parties (author biographies, book covers, Wikipedia excerpts)
            remains the property of the respective rights holders and is used under applicable fair
            use, open licence, or API terms of service provisions.
          </p>
        </Section>

        <Section title="6. Third-Party Services and Links">
          <p>
            The Service integrates with and links to third-party services including Dropbox, Google
            Drive, Wikipedia, Amazon, and others. These services are governed by their own terms and
            privacy policies. We are not responsible for the content, availability, or practices of
            any third-party service.
          </p>
        </Section>

        <Section title="7. AI-Generated Content Disclaimer">
          <p>
            The Service uses artificial intelligence to generate author biographies, book summaries,
            interest analyses, and other content. While we strive for accuracy, AI-generated content
            may contain errors, omissions, or outdated information. You should independently verify
            any AI-generated content before relying on it for important decisions.
          </p>
          <p>
            AI-generated content does not constitute professional advice of any kind — financial,
            legal, medical, or otherwise.
          </p>
        </Section>

        <Section title="8. Data and Privacy">
          <p>
            Your use of the Service is also governed by our{" "}
            <Link href="/privacy">
              <span className="text-primary underline underline-offset-2 cursor-pointer">Privacy Policy</span>
            </Link>
            , which is incorporated into these Terms by reference. By using the Service, you consent
            to the collection and use of your information as described in the Privacy Policy.
          </p>
        </Section>

        <Section title="9. Disclaimers and Limitation of Liability">
          <p>
            The Service is provided "as is" and "as available" without warranties of any kind, either
            express or implied. We do not warrant that the Service will be uninterrupted, error-free,
            or free of viruses or other harmful components.
          </p>
          <p>
            To the fullest extent permitted by applicable law, {COMPANY_NAME} shall not be liable for
            any indirect, incidental, special, consequential, or punitive damages arising out of or
            related to your use of the Service, even if we have been advised of the possibility of
            such damages.
          </p>
        </Section>

        <Section title="10. Governing Law">
          <p>
            These Terms shall be governed by and construed in accordance with the laws of the
            jurisdiction in which {COMPANY_NAME} is registered, without regard to its conflict of
            law provisions. Any disputes arising under these Terms shall be subject to the exclusive
            jurisdiction of the courts in that jurisdiction.
          </p>
        </Section>

        <Section title="11. Changes to These Terms">
          <p>
            We may revise these Terms at any time. When we do, we will update the "Last updated"
            date at the top of this page. Material changes will be communicated via a notice within
            the Service. Your continued use of the Service after any changes constitutes acceptance
            of the new Terms.
          </p>
        </Section>

        <Section title="12. Contact Us">
          <p>
            If you have questions about these Terms of Service, please contact us:
          </p>
          <address className="not-italic text-sm space-y-1">
            <div><strong>{COMPANY_NAME}</strong></div>
            <div>
              Email:{" "}
              <a href={`mailto:${CONTACT_EMAIL}`} className="text-primary underline underline-offset-2">
                {CONTACT_EMAIL}
              </a>
            </div>
            <div>
              Website:{" "}
              <a href={COMPANY_WEBSITE} target="_blank" rel="noopener noreferrer" className="text-primary underline underline-offset-2">
                {COMPANY_WEBSITE}
              </a>
            </div>
          </address>
        </Section>

        {/* Footer */}
        <footer className="pt-8 border-t border-border text-xs text-muted-foreground flex flex-wrap items-center justify-between gap-4">
          <span>© {new Date().getFullYear()} {COMPANY_NAME}. All rights reserved.</span>
          <div className="flex items-center gap-4">
            <Link href="/privacy">
              <span className="hover:text-foreground transition-colors cursor-pointer">Privacy Policy</span>
            </Link>
            <Link href="/cookies">
              <span className="hover:text-foreground transition-colors cursor-pointer">Cookie Policy</span>
            </Link>
            <Link href="/">
              <span className="hover:text-foreground transition-colors cursor-pointer">← Back to {APP_NAME}</span>
            </Link>
          </div>
        </footer>
      </main>
    </div>
  );
}

// ── Helper components ──────────────────────────────────────────────────────────

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-4">
      <h2 className="text-xl font-semibold tracking-tight border-b border-border pb-2">{title}</h2>
      <div className="space-y-3 text-sm leading-relaxed text-foreground/90">{children}</div>
    </section>
  );
}
