/**
 * Google Imagen / Nano Banana Image Generator
 *
 * Supports all Google Gemini image generation models:
 *   - gemini-2.5-flash-image  (Nano Banana — default, fast, high quality)
 *   - gemini-3-pro-image-preview  (Nano Banana Pro — higher quality, slower)
 *   - imagen-3.0-generate-001  (Imagen 3 — dedicated image model)
 *
 * Uses the @google/genai SDK with responseModalities: ["IMAGE", "TEXT"].
 * Returns base64-encoded image bytes.
 */

import { GoogleGenAI } from "@google/genai";
import {
  ImageGenerator,
  ImageGeneratorConfig,
  ImageGenerationRequest,
  ImageGenerationResult,
} from "../types.js";

export const GOOGLE_MODELS: Record<string, string> = {
  "nano-banana": "gemini-2.5-flash-image",
  "nano-banana-pro": "gemini-3-pro-image-preview",
  "imagen-3": "imagen-3.0-generate-001",
  // Allow passing model IDs directly
  "gemini-2.5-flash-image": "gemini-2.5-flash-image",
  "gemini-3-pro-image-preview": "gemini-3-pro-image-preview",
  "imagen-3.0-generate-001": "imagen-3.0-generate-001",
};

export const DEFAULT_GOOGLE_MODEL = "gemini-2.5-flash-image";

export class GoogleImagenGenerator implements ImageGenerator {
  private readonly model: string;

  constructor(config: ImageGeneratorConfig) {
    // Resolve friendly names to actual model IDs
    this.model = GOOGLE_MODELS[config.model] ?? config.model ?? DEFAULT_GOOGLE_MODEL;
  }

  isAvailable(): boolean {
    return !!process.env.GEMINI_API_KEY;
  }

  async generate(request: ImageGenerationRequest): Promise<ImageGenerationResult> {
    const startTime = Date.now();
    const apiKey = process.env.GEMINI_API_KEY;

    if (!apiKey) {
      return {
        mimeType: "image/png",
        vendor: "google",
        model: this.model,
        durationMs: Date.now() - startTime,
        error: "GEMINI_API_KEY is not set",
      };
    }

    try {
      const ai = new GoogleGenAI({ apiKey });

      // For Imagen 3, use the dedicated generateImages API
      if (this.model.startsWith("imagen-")) {
        const response = await ai.models.generateImages({
          model: this.model,
          prompt: request.prompt,
          config: {
            numberOfImages: 1,
            aspectRatio: request.aspectRatio ?? "1:1",
          },
        });

        const image = response.generatedImages?.[0];
        if (!image?.image?.imageBytes) {
          return {
            mimeType: "image/png",
            vendor: "google",
            model: this.model,
            durationMs: Date.now() - startTime,
            error: "No image generated by Imagen",
          };
        }

        return {
          imageBase64: image.image.imageBytes,
          mimeType: "image/png",
          vendor: "google",
          model: this.model,
          durationMs: Date.now() - startTime,
        };
      }

      // For Gemini image models (Nano Banana), use generateContent with IMAGE modality
      const response = await ai.models.generateContent({
        model: this.model,
        contents: [
          {
            role: "user",
            parts: [{ text: request.prompt }],
          },
        ],
        config: {
          responseModalities: ["IMAGE", "TEXT"],
        },
      });

      const candidates = response.candidates ?? [];
      for (const candidate of candidates) {
        for (const part of candidate.content?.parts ?? []) {
          if (part.inlineData?.data && part.inlineData?.mimeType) {
            return {
              imageBase64: part.inlineData.data,
              mimeType: part.inlineData.mimeType,
              vendor: "google",
              model: this.model,
              durationMs: Date.now() - startTime,
            };
          }
        }
      }

      return {
        mimeType: "image/png",
        vendor: "google",
        model: this.model,
        durationMs: Date.now() - startTime,
        error: "No image part found in Gemini response",
      };
    } catch (err) {
      return {
        mimeType: "image/png",
        vendor: "google",
        model: this.model,
        durationMs: Date.now() - startTime,
        error: err instanceof Error ? err.message : "Unknown error",
      };
    }
  }
}
